# steps:
#   # Install dependencies
#   - name: continuumio/anaconda3
#     entrypoint: pip
#     args: ["install", "-r", "requirements.txt", "--user"]
#   # Lark test
#   - name: continuumio/anaconda3
#     entrypoint: python
#     args: ["lark_test.py"]
#   # [START cloudbuild_python_tests_yaml]
#   # # Run unit tests
#   # - name: python
#   #   entrypoint: python
#   #   args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"] 
#   # # [END cloudbuild_python_tests_yaml]

#   - name: continuumio/anaconda3
#     entrypoint: python
#     args: ["temp.py"]
#   # [END cloudbuild_python_tests_yaml]


  
#   # - name: 'gcr.io/cloud-builders/docker'
#   #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/imgwebapp:v1', '.']
#   #   timeout: 180s
#   # - name: "gcr.io/cloud-builders/gke-deploy"
#   #   args:
#   #   - run
#   #   - --filename=k8s/
#   #   - --location=us-west1
#   #   - --cluster=project-kube

#NEW CODE:-----------------------------------------------------------------------------
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/imgwebapp:v1', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/imgwebapp:v1']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built"
    ls -la
    ls -al models/
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s/
  - --location=us-west1
  - --cluster=ml-pipeline

   
