apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/sodium-reporter-331815/imgwebapp:v5
        ports:
        - containerPort: 8501